server:
  port: 10030

spring:
  datasource: # mysql配置
    url: jdbc:mysql://localhost:3306/judicial_learning?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Wei20021016
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis: #redis连接
      host: 127.0.0.1
      port: 6379
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      # password: "123456"
      lettuce:
        pool:
          # 最大阻塞等待时间，负数表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 5
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
          max-active: 20


    mongodb:  #mongodb连接
      database: Judicial_learning
      host: 127.0.0.1
      port: 27017
  application:
    name: judicial_learning
  servlet:
    multipart:
      max-file-size: 10MB   # 单个文件上传的最大上限
      max-request-size: 100MB  # 整个请求体的最大上限


minio: #   minio配置
  url: http://192.168.186.161:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: file-video-test

mybatis-plus: #mybatis-plus 配置
  type-aliases-package: com.he.domin.entity.mysql
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.he.controller # 扫描的包，注意改成自己的包
#    - group: "管理端"
#      paths-to-match: '/admin/**'
#      packages-to-scan: com.my.controller
#    - group: "用户端"
#      paths-to-match: '/user/**'
#      packages-to-scan: com.my.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
